server:
  servlet:
    context-path: /budget-manager
  port: 8080

spring:
  liquibase:
    contexts: development
  datasource:
    url: jdbc:postgresql://localhost:5432/budget-manager
    username: postgres
    password: MANAGER
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      show-sql: true
      hibernate:
        format_sql: true
        generate_statistics: true
        dialect: org.hibernate.dialect.PostgreSQL95Dialect

